wordcount -i -new xaa
wordcount -i -add xab
wordcount -i -add xac
wordcount -i -add xad
wordcount -i -add xae
wordcount -i -add xaf
wordcount -i -add xag
wordcount -i -add xah
wordcount -i -add xai
wordcount -i -add xaj
wordcount -i -add xak
wordcount -i -add xal
wordcount -i -add xam
wordcount -i -add xan
wordcount -i -add xao
wordcount -i -add xap
wordcount -i -add xaq
wordcount -i -add xar
wordcount -i -add xas
wordcount -i -add xat
wordcount -i -add xau
wordcount -i -add xav
wordcount -i -add xaw
wordcount -i -add xax
wordcount -i -add xay
wordcount -i -add xaz
wordcount -i -add xba
wordcount -i -add xbb
wordcount -i -add xbc
wordcount -i -add xbd
wordcount -i -add xbe
wordcount -i -add xbf
wordcount -i -add xbg
wordcount -i -add xbh
wordcount -i -add xbi
wordcount -i -add xbj
wordcount -i -add xbk
wordcount -i -add xbl
wordcount -i -add xbm
wordcount -i -add xbn
wordcount -i -add xbo
wordcount -i -add xbp
wordcount -i -add xbq
wordcount -i -add xbr
wordcount -i -add xbs
wordcount -i -add xbt
wordcount -i -add xba
wordcount -i -add xbu
wordcount -i -add xbv
wordcount -i -add xbw
wordcount -i -add xbx
wordcount -i -add xby
wordcount -i -add xcz
wordcount -i -add xca
wordcount -i -add xcb
wordcount -i -add xcc
wordcount -i -add xcd
wordcount -i -add xce
wordcount -i -add xcf
wordcount -i -add xcg
wordcount -i -add xch
wordcount -i -add xci
wordcount -i -add xcj
wordcount -i -add xck
wordcount -i -add xcl
wordcount -i -add xcm
wordcount -i -add xcn
wordcount -i -add xco
wordcount -i -add xcp
wordcount -i -add xcq
wordcount -i -add xcr
wordcount -i -add xcs
wordcount -i -add xcu
wordcount -i -add xcv
wordcount -i -add xcw
wordcount -i -add xcx
wordcount -i -add xcy
wordcount -i -add xcz
wordcount -i -add xda
wordcount -i -add xdb
wordcount -i -add xdc
wordcount -i -add xdd
wordcount -i -add xde
wordcount -i -add xdf
wordcount -i -add xdg
wordcount -i -add xdh
wordcount -i -add xdi
wordcount -i -add xdj
wordcount -i -add xdk
wordcount -i -add xdl
wordcount -i -add xdm
wordcount -i -add xdn
wordcount -i -add xdo
wordcount -i -add xdp
wordcount -i -add xdq
wordcount -i -add xdr
wordcount -i -add xds
wordcount -i -add xdt
wordcount -i -add xdu
wordcount -i -add xdv
wordcount -i -add xdw
wordcount -i -add xdx
wordcount -i -add xdy